name: Java CI with Maven, Docker, and EKS Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ECR_REPOSITORY: rk-poc-ecr
  EKS_CLUSTER_NAME: rk-poc
  DOCKER_REPOSITORY: umairhameed/github-spring-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-build-artifact
          path: target/*.jar
